<?php

namespace Pois\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationSubscriptionRepository extends EntityRepository
{

	public function findOneByUserAndNotification($notificationId, $userId)
	{
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('ns')
            ->from('PoisNotificationBundle:NotificationSubscription', 'ns')
            ->where('ns.notification = :notificationId')
            ->andWhere('ns.user = :userId')
            ->setParameter('notificationId', $notificationId)
            ->setParameter('userId', $userId);

        $result =  $qb->getQuery()->getResult();
        return count($result)?array_shift($result):null;
	}
}
