<?php

namespace Pois\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

	public function findByService($serviceName) 
	{
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('n')
            ->from('PoisNotificationBundle:Notification', 'n')
            ->innerJoin('n.notificationType','nt')
            ->where('nt.service = :serviceName')
            ->orderBy('n.id', 'ASC')
            ->setParameter('serviceName', $serviceName);

        return $qb->getQuery()->getResult();		
	}
}
